name: Sensing dev installer Build, Test

on:
  push:
    branches:
      - '*'  # This will run the build and test jobs for every push on all branches

  pull_request:
    branches:
      - '*'  # This will run the build and test jobs for pull requests to all branches


jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
         python-version: "3.11.4"

      - name: Install Conan and PyYAML via pip
        run: |
         python -m pip install conan
         python -m pip install PyYAML

      - name: Disable Perl (remove from PATH)
        run: choco uninstall strawberryperl -n

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Create and enter the build directory
        run: |
          cd installer
          mkdir build
          cd build

      - name: Run CMake
        working-directory: installer/build
        run: cmake -G "Visual Studio 17 2022" -A x64 ../

      - name: Build with CMake
        working-directory: installer/build
        run: cmake --build . --config Release

      - name: Generate liscence files
        working-directory: installer/build
        run: cmake -G "Visual Studio 17 2022" -A x64 ../ 

      - name: Package with CPack WIX
        working-directory: installer/build
        run: cpack -G "WIX"

      - name: Upload artifacts MSI
        uses: actions/upload-artifact@v2
        with:
          name: sensing-dev-installer-msi
          path: |
            installer/build/*.msi

      - name: Create package zip
        working-directory: installer/build
        run: cpack -G "ZIP"

      - name: Create package without opencv
        working-directory: installer/build
        run:  cmake -G "Visual Studio 17 2022" -A x64 ../ -DOPENCV_ACTION="use_existing"

      - name: Create package msi
        working-directory: installer/build
        run: cpack -G "WIX"

      - name: Create package zip
        working-directory: installer/build
        run: cpack -G "ZIP"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: sensing-dev-installer-zip
          path: |
            installer/build/*.zip

      
            
  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Run tests
        run: |
          echo "TODO : Running tests..."

  




