name: Sensing dev installer Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # vYY.MM.Patch example v23.08.00 etc.

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
         python-version: "3.11.4"

      - name: Install Conan and PyYAML via pip
        run: |
         python -m pip install conan
         python -m pip install PyYAML

      - name: Disable Perl (remove from PATH)
        run: choco uninstall strawberryperl -n

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Create and enter build directory
        run: |
          cd installer
          mkdir build
          cd build

      - name: Run CMake
        working-directory: installer/build
        run: cmake -G "Visual Studio 17 2022" -A x64 ../

      - name: Build
        working-directory: installer/build
        run: cmake --build . --config Release 

      - name: Generate liscence files
        working-directory: installer/build
        run: cmake -G "Visual Studio 17 2022" -A x64 ../ 

      - name: Create package msi
        working-directory: installer/build
        run: cpack -G "WIX"

      - name: Create package zip
        working-directory: installer/build
        run: cpack -G "ZIP"

      - name: Create package without opencv
        working-directory: installer/build
        run:  cmake -G "Visual Studio 17 2022" -A x64 ../ -DOPENCV_ACTION="use_existing"

      - name: Create package msi
        working-directory: installer/build
        run: cpack -G "WIX"

      - name: Create package zip
        working-directory: installer/build
        run: cpack -G "ZIP"

      - name: Release      
        uses: softprops/action-gh-release@v1
        with:
          files: |
            installer/tools/installer*.ps1
            installer/build/*.msi
            installer/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Test Workflow
        shell: pwsh
        env:
          SCRIPT_OPTIONS: '["-user $env:USERNAME", "-user $env:USERNAME -InstallOpenCV", "", "-InstallOpenCV"]'
        run: |
          # PowerShell code to construct and send the request
          $scriptOptions = $env:SCRIPT_OPTIONS -replace '\$env:USERNAME', $env:USERNAME
          $jsonPayload = @{
            ref = "${{ github.head_ref }}"
            inputs = @{
              versions = "${{ github.ref_name }}"
              options = $scriptOptions
            }
          } | ConvertTo-Json -Compress
          
          curl -X POST `
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
                -H "Accept: application/vnd.github.v3+json" `
                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Test-Release.yml/dispatches" `
                -d $jsonPayload
          


